<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<?=$this->headTitle()?>
	<?=$this->headLink()?>
	<meta name="description" content="Zend Framework Form Generator" /> 
	<meta name="keywords" content="Zend Framework, Zend, form, форма, генератор, generator, Zend_Form" /> 
	<meta name="robots" content="noodp,noydir" />
</head>
<body>
	<h1>Zend Framework Form Generator</h1>
	<?=$this->layout()->content?>
	<?=$this->headScript()?>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21499766-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- Yandex.Metrika counter -->
<div style="display:none;"><script type="text/javascript">
(function(w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter4551391 = new Ya.Metrika(4551391);
             yaCounter4551391.clickmap(true);
             yaCounter4551391.trackLinks(true);
        
        } catch(e) { }
    });
})(window, 'yandex_metrika_callbacks');
</script></div>
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
<noscript><div style="position:absolute"><img src="//mc.yandex.ru/watch/4551391" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>
